services:
  db:
    image: postgres:16-alpine
    container_name: inventario_db
    environment:
      POSTGRES_USER: inventario
      POSTGRES_PASSWORD: inventario123
      POSTGRES_DB: inventario_db
    ports:
      - "5432:5432"
    volumes:
      - inventario_pg:/var/lib/postgresql/data

volumes:
  inventario_pg: